eureka:
  instance:
    prefer-ip-address: true
    hostname: service-registry
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
